datasrc.username=BRBSDB
datasrc.password=brbs
datasrc.url=jdbc:oracle:thin:@122.165.217.18:1521/ASPIRA
default.password=Bornfire@123
default.pagesize=5000



output.exportpath=C:/
output.exportpathfinal=C:/RT_REPORT/FINALTEMP/
output.exportpathtemp=C:/RT_REPORT/SOURCETEMP/


#Session
spring.session.store-type=jdbc
spring.session.timeout=18000

#Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.open-in-view=false


#Server
server.servlet.context-path=/AccountStatement

#server.port=8081
server.port=8086

#Security
spring.resources.add-mappings=true


#Logging
debug=false

#File upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

mail.host=mail.bornfire.co.in
mail.port=587
mail.username=nandhini.j@bornfire.co.in
mail.password=Bornfire#123



spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Disable default Whitelabel error page
server.error.whitelabel.enabled=false
server.error.path=/error

#logging.level.org.thymeleaf=DEBUG
